package io.lms.coursecatalogservice.model;

import javax.persistence.*;
import java.time.Instant;
import java.util.List;

@Entity
public class Course
{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    private String name;
    private String description;
    private String author;             //ToDo :- This details needs to be fetched from User Management Service (Using login details)
    private String url;                 //ToDo :- How to build this URL(And why it is required)
    private Instant createDate;           //ToDo :- Who has to enter CreateDate (Or should it get autogenerated)
    private int likeCount;
    private int dislikeCount;
    private int shareCount;
    @OneToMany
    List<Chapter> chapters;


    public Course()
    {

    }

    public Course(String name, String description, String author)
    {
        this.name = name;
        this.description = description;
        this.author = author;
    }

    //To Auto-Generate Date

    @PrePersist
    public void prePersist()
    {
        createDate = Instant.now();
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public String getUrl()
    {
        return url;
    }

    public void setUrl(String url)
    {
        this.url = url;
    }

    public String getAuthor()
    {
        return author;
    }

    public void setAuthor(String author)
    {
        this.author = author;
    }

    public int getLikeCount()
    {
        return likeCount;
    }

    public void setLikeCount(int likeCount)
    {
        this.likeCount = likeCount;
    }

    public int getDislikeCount()
    {
        return dislikeCount;
    }

    public void setDislikeCount(int dislikeCount)
    {
        this.dislikeCount = dislikeCount;
    }

    public int getShareCount()
    {
        return shareCount;
    }

    public void setShareCount(int shareCount)
    {
        this.shareCount = shareCount;
    }

    public Instant getCreateDate()
    {
        return createDate;
    }
}